version: "3.6"
services:

  #1
  #books service
  app_books:
    container_name: flask_app_books
    build: 
      context: ./books
      dockerfile: Dockerfile
    command: python -u main.py
    ports:
      - "8000:5000"
    volumes:
      - .:/app
    links:
      - db_books
  db_books:
    container_name: flask_app_books_db
    image: mysql:5.7
    volumes:
      - DB_books_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_01  
      MYSQL_PASSWORD: root
    ports: 
      - "3306:3306"

  #2
  #borrowing service
  app_borrowing:
    container_name: flask_app_borrowing
    build: 
      context: ./borrowing
      dockerfile: Dockerfile
    command: python -u main.py
    ports:
      - "8001:5000"
    volumes:
      - .:/app
    links:
      - db_borrowing
  db_borrowing:
    container_name: flask_app_borrowing_db
    image: mysql:5.7
    volumes:
      - DB_borrowing_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_01  
      MYSQL_PASSWORD: root
    ports: 
      - "3307:3307"
  
  #3
  #customer service
  app_customer:
    container_name: flask_app_customer
    build: 
      context: ./customer
      dockerfile: Dockerfile  
    command: python -u main.py
    ports:
      - "8002:5000"
    volumes:
      - .:/app
    links:
      - db_customer
  db_customer:
    container_name: flask_app_customer_db
    image: mongo:4.0.27
    hostname: library_db
    environment:
      - MONGO_INITDB_DATABASE=library_db
    volumes:
      - DB_customer_data:/data/db
    ports:
      - "27017:27017"

  #4
  #notification service
  rabbitmq:
    image: rabbitmq:3.8.19-rc.1-management-alpine
    container_name: 'rabbitmq'
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq



volumes:
  DB_books_data : {}
  DB_borrowing_data : {}
  DB_customer_data : {}