version: "3.7"
services:
  app:
    build: .
    command: python -u main.py
    ports:
      - "S5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:8      
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    environment:
        MYSQL_DATABASE: video_db
        MYSQL_ROOT_PASSWORD: rootpass
        MYSQL_USER: dbuser
        MYSQL_PASSWORD: userpass
    ports:
    - "3306:3306"
    volumes:
    - ./root/docker/db/conf.d:/etc/mysql/conf.d
    - ./storage/docker/mysql-data:/var/lib/mysql







