version: '2.3'

services:
  sql-server-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "super_duper_password"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Express
