version: '2.3'

services:
    mysql:
      image: mysql:8
      container_name: prestashop-db
      command: --default-authentication-plugin=mysql_native_password
      environment:
        MYSQL_DATABASE: prestashop
        MYSQL_ROOT_PASSWORD: prestashop
      ports:
        - 3306:3306
      networks:
        - prestashop



networks:
  prestashop:

