name: CI-CD

on: # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}   
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: docker build 1
      run: |
        docker build ./TEST_FINALE/books -t ${{ secrets.DOCKER_USER }}/test_finale_app_books
    - name: docker build 2
      run: |
        docker build ./TEST_FINALE/customer -t ${{ secrets.DOCKER_USER }}/test_finale_app_customer
    - name: docker build 3
      run: |
       docker build ./TEST_FINALE/borrowing -t ${{ secrets.DOCKER_USER }}/test_finale_app_borrowing
    - name: docker push
      run: |
        docker push ${{ secrets.DOCKER_USER }}/test_finale_app_books
        docker push ${{ secrets.DOCKER_USER }}/test_finale_app_customer
        docker push ${{ secrets.DOCKER_USER }}/test_finale_app_borrowing
